### PR TITLE
Allow specifying file name and type for outputs

### LINKED ISSUE #14: Model output format
Hi, 
thanks a lot for this interesting project.

We are testing some QGIS models. In QGIS I can choose as output whether to create a temporary layer, generate a gpkg or save with another format (e.g. csv). 
image

With py-qgis-wps, I always get the result as gpkg. If I define the parameter of the output file such as `file.csv`, a gpkg with a layer called "file.csv" is created instead of a csv file.

Is it possible to specify somehow what the desired output format should be?

### PR DESCRIPTION
**Pull request by m-kuhn**
by prefixing them with `file://`

Fixes #14

### CODE REVIEW

**Comment by dmarteau** [comment]
Hi Matthias.

See my comment about this https://github.com/3liz/py-qgis-wps/issues/14#issuecomment-839620400

**Comment by dmarteau** [comment]
There would also be a possibility to release the constraint about passing a file name/path with an explicit options: but this would be a dangerous option and it would mean to control your WPS workflow.

**Comment by m-kuhn** [comment]
@dmarteau an explicit option would work perfectly fine for our scenario, since we don't publicly expose the service. I'll comment a bit more detailed in #14

**Comment by dmarteau** [comment]
@m-kuhn do you want to handle it ? Otherwise, in all cases I have to work on some related issue.

**Comment by m-kuhn** [comment]
That would be very nice, thanks @dmarteau . Let me know if I can help with anything!

Just to be sure, it will be

- a config option set (`QGSWPS_NO_STRICT_PARAM_CHECKS` or similar?)
- the path can be specified as `<wps:LiteralData>"/io/result.csv"</wps:LiteralData>`

**Comment by dmarteau** [comment]
> a config option set (QGSWPS_NO_STRICT_PARAM_CHECKS or similar?)

yes

> the path can be specified as <wps:LiteralData>"/io/result.csv"</wps:LiteralData>

To be practical it should be the value passed as literal input, so yes (and then drop the model option). 

But that will also override the name used as layer name (i.e `destinationName`) in the resulting output project, so I have to figure out how to handle this.

**Comment by dmarteau** [comment]
@m-kuhn could you have a look at #16 and tell if that fit your needs ?

**Comment by dmarteau** [comment]
Fixed by #16

**Comment by m-kuhn** [comment]
Thanks for taking over

**Pull request closed without merging**
