### PR TITLE
Allow unsafe option for destination layer

### LINKED ISSUE #14: Model output format
Hi, 
thanks a lot for this interesting project.

We are testing some QGIS models. In QGIS I can choose as output whether to create a temporary layer, generate a gpkg or save with another format (e.g. csv). 
image

With py-qgis-wps, I always get the result as gpkg. If I define the parameter of the output file such as `file.csv`, a gpkg with a layer called "file.csv" is created instead of a csv file.

Is it possible to specify somehow what the desired output format should be?

### PR DESCRIPTION
**Pull request by dmarteau**
##  Summary

* Allow passing sink definition as input value
* Allow defining default extension for raster/vector files.
* Preserve file extension for output definition with models.

* Ticket : fix #14 

## Description

 This PR creates the new parameters:
 
* PROCESSING_RAW_DESTINATION_INPUT_SINK: 
        Allow input value as sink for destination layers.
        This allow value passed as input value to be interpreted as
        path or uri sink definition. This enable passing any string
        that Qgis may use a input source but without open options except for the
        'layername=<name>' option.
        Running concurrent jobs with this option may result in unpredictable
        behavior.
        For that reason it is considered as an UNSAFE OPTION and you should never enable this option
        if you are exposing the service publicly.
        File path prefixed with '/' will correspond to path located in the root directory specified by
        the `PROCESSING_DESTINATION_ROOT_PATH` option. Otherwise, they will be stored in the job folder.

* PROCESSING_DESTINATION_ROOT_PATH:
        Specify the root directory for storing destination layers files when
        the `PROCESSING_RAW_DESTINATION_INPUT_SINK` option is enabled.
        If not specified, file will be stored in the job folder.

### CODE REVIEW

**Comment by m-kuhn** [comment]
Nice, looks good codewise.
The env var name looks a bit scary. I wonder if the term "unsafe" could be replaced with "unmanaged" or "raw". Where I'm going to is that in cases where it actually IS safe and justified this option will still ring alarm bells everywhere.

**Comment by dmarteau** [comment]
> this option will still ring alarm bells everywhere.

That's the idea, 

From a server security point of view, this is really an unsafe options and a very dangerous open door:  for someone using it without knowing exactly what it is doing it could be desastrous: running as root and publicly open then it may overwrite any system file. This is without counting the fact that it defeats concurrency by potentially accessing the  same file in write mode by several processes.

So this is indeed a very *unsafe* option, I was very reluctant to enable such an option at the beginning, but I feel that it may cover many use cases where the workflow is very controlled, as  you do.

I know that people exactly knowing what they are doing are not  affraid by scary names :-). And scary name is doing exactly what I want: scaring people that  are not so sure are what they are doing.....

**Comment by m-kuhn** [comment]
I was thinking: if it's opt in you HAVE to read the docs to know about it. And you get a warning on startup.
Or call it "disable safe mode" instead which is a bit less scary.

I could also live with csv in the job folder. Which would be safe too. Even better if it's in the response. How would that sound. It's mainly for data that is trivial and gpkg is harder to process/inspect by non-geo-external-ifaces.

But I'll trust you in the end 😃

**Comment by dmarteau** [comment]
> Even better if it's in the response. 

That's the next step => choose between file or wms url as response. A a matter of fact this is already possible to select the url form of the response and it must be possible to respond with  content  (or ref to content) without much work for layers - I'm on it right now

> I could also live with csv in the job folder

I would be much more comfortable with that solution, if it fits the use cases, then the option will allow you to pass the name of the destination file but still restricted to the job folder.
 
 Note that this PR also make some changes so that the file type is preserved from the model options (if you have specified a csv then it will be a csv file, wich is the original issue raised in #14)

**Comment by m-kuhn** [comment]
That sounds perfect. If the absolute pathe can be assembled from the job response and known prefix path.

I think specifying the (unsafe) absolute path still makes sense for some use cases so I wouldn't completely remove it.

**Comment by dmarteau** [comment]
@m-kuhn  By the way, there is a download api that enable you to retrieve any file from the job folder, it is mainly used when files are returned by reference (which is the default).

**Comment by m-kuhn** [comment]
Ah nice, didn't know about it.

**Comment by dmarteau** [comment]
I can think about a very simple way to keep destination path secure while allowing absolute path: define a ROOT_DESTINATION_PATH under which files may be  saved outside the job folder.

**Comment by dmarteau** [comment]
> Ah nice, didn't know about it.

The url is `/store/{uuid}/{file}` where uuid is the uuid of the job (from the execute response) -- if {file} is not given you will have the content of the job folder. 

You may also check the web interface for monitoring the jobs:  `/ui/`

**Comment by m-kuhn** [comment]
> I can think about a very simple way to keep destination path secure while allowing absolute path: define a ROOT_DESTINATION_PATH under which files may be saved outside the job folder.

Then one needs to be able to specify if files go to root des path or job folder somehow. If that's possible that solution would fit all needs.

**Comment by dmarteau** [comment]
> Then one needs to be able to specify if files go to root des path or job folder somehow. If that's possible that solution would fit all needs.

Yes, this is indeed the case for files if they are prefixed with '/', otherwise they will be located in the job folder (see description above).

**Pull request merged**
